spring:
  datasource:
    url: jdbc:mysql://10.16.2.24:3306/piaoeda_admission?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true&amp;useSSL=false&amp;serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234.